version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: enzocam
      MONGO_INITDB_ROOT_PASSWORD: nocenzo
    volumes:
      - ./mongo/data/db:/data/db
    ports: 
      - 27018:27017